---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: demo
  become: yes
  connection: ssh
  #remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
